
services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_defender
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - code_defender_network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - code_defender_network

  api:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm prisma:generate && pnpm start:dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/code_defender?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRATION=86400
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - code_defender_network

networks:
  code_defender_network:

volumes:
  postgres_data:
  node_modules:
